name: Second

on:
  workflow_run:
    workflows: ["First"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running after first workflow!"
